[package]
name = "easypwned"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "*"
axum = "0.6.*"
tokio = { version = "1.*", features = ["full"]}
serde = "1.*"
serde_json = "1.*"
serde_derive = "1.*"
tracing = "0.1.*"
sha-1 = "0.*"
base16ct = { version = "0.2", features = ["alloc", "std"]}
structopt = "0.*"
easypwned_bloom = {path = "../easypwned_bloom"}